#!/bin/bash

set -e

tag=$1

if [[ -z "$tag" ]]; then
  tag=$(cat .version)
fi

CONFIG_FILE="config/secret-prod.yaml"

name=$(yq .name < $CONFIG_FILE)
project_id=$(yq .project_id < $CONFIG_FILE)
location=$(yq .location < $CONFIG_FILE)
img="${location}-docker.pkg.dev/${project_id}/${name}/app"

printf "Checking if image $img:$tag exists..."

reg_tag=$(gcloud container images list-tags --filter="tags:$tag" --format=json $img)

printf "Tag:" $(echo $reg_tag | jq -r '.[0].digest')


if [[ "$reg_tag" == "[]" ]]; then
  printf "Image tag $tag does not exist, aborting\n"
  exit 1
fi

printf "\nApplying terraform..."
terraform -chdir=./deployment/demo apply -auto-approve
