#!/bin/bash

set -u
set -e

img=$1
tag=$2

reg_tag=$(gcloud container images list-tags \
			--filter="tags:$tag" \
			--format=json $img)

printf "Tag:" $(echo $reg_tag | jq -r '.[0].digest')


if [[ "$reg_tag" == "[]" ]]; then
  printf "Image tag $tag does not exist, aborting\n"
  exit 1
fi

printf "\nApplying terraform..."
terraform -chdir=./deployment apply -auto-approve
