#!/bin/bash

gh secret set DB_CLIENT_KEY < keys/private_key.key
gh secret set DB_CLIENT_PEM < keys/public_cert.pem
gh secret set DB_CA_PEM < keys/server_ca.pem

chmod 600 keys/*

INSTANCE_IP=$(gcloud sql instances describe $INSTANCE \
    --format='value(ipAddresses[0].ipAddress)')

gh secret set DB_IP --body "${INSTANCE_IP}"

echo "CONNECTION STRING:"
echo "psql \"sslmode=verify-ca sslrootcert=keys/server_ca.pem sslcert=keys/public_cert.pem sslkey=keys/private_key.key hostaddr=${INSTANCE_IP} port=5432 dbname=vul\""
