#!/bin/bash

set -u
set -e

echo "Waiting for GitHub workflow to start..."
sleep 5

s=""
while [ "$s" !=	"completed" ]
do
	sleep 7
  	s=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/mchmarny/vul/actions/runs | jq -r '[.workflow_runs[] | select(.name == "on_tag")] | .[0].status')
	echo "Status: $s"
done


c=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/mchmarny/hn/actions/runs | jq -r '[.workflow_runs[] | select(.name == "on_tag")] | .[0].conclusion')

if [ "$c" != "success" ]
then
	echo "Publish failed. See github logs for details:"
	echo "https://github.com/mchmarny/vul/actions/workflows/on-tag.yaml"
	exit 1
fi