---
name: vul
project_id: s3cme1
runtime:
  log_level: debug
  external_url: http://localhost:8080
  send_metrics: false
store:
  type: postgres
  user: vimp
  password: test
  db: vimp
  host: localhost
app:
  image_timeline_days: 30
  image_version_limit: 30
