---
name: vul
project_id: s3cme1
runtime:
  log_level: debug
  external_url: http://localhost:8080
  send_metrics: false
store:
  uri: postgres://vimp:test@localhost:5432/vimp
pubsub:
  topic: vul-image-queue
  post: false
app:
  image_timeline_days: 30
  image_version_limit: 30
worker:
  scanner:
    env_vars:
      - "SNYK_TOKEN=test"
