# This file is for tests only, ok to commit it to source control.
# Should not need to update these values.
---
name: vul
project_id: test  # update this to your GCP project ID
location: test  # update this to your GCP location (aka region)
runtime:
  log_level: debug
  send_metrics: false
store:
  type: postgres
  user: postgres
  password: test
  db: vul
  instance: localhost
  host: localhost
  port: 5432
app:
  image_timeline_days: 30
  image_version_limit: 30
import:
  snyk_token: test
