---
name: vul
project_id: sample  # UPDATE: your GCP project ID
location: us-west1  # UPDATE: your GCP location (aka region)
runtime:
  log_level: debug
  send_metrics: true  # UPDATE: whether or not you want to collect Cloud Metrics
store:
  type: postgres
  user: postgres
  password: test  # UPDATE: your preferred postgres password, make it strong
  db: vul
  path: /cloudsql/  # this is only used in Cloud Run (don't change it)
  instance: SQL_INSTANCE  # this will be set automatically during deployment
  host: "PRIVATE_IP"  # this will be set automatically during deployment
  port: 5432
app:
  image_timeline_days: 30  # UPDATE: how many days of image history do you want to display in the UI
  image_version_limit: 10  # UPDATE: how many image versions do you want to display in the UI
import:
  snyk_token: "test"  # UPDATE: your Snyk API token
