#!/bin/bash

# cloud sql config
export INSTANCE="vul"
export HOME_DIR="${HOME}/.cloud-sql"
export NUMBER_CPUS="2"
export MEMORY_SIZE="7680MB"
export NODE_ZONE="us-west1-c"
export NODE_HD="100GB" #initial only, will auto-grow
export DB_NAME="vul"
export DB_USER="app"
export DB_VERSION="POSTGRES_14"
export DB_BUCKET="vuln-db-dumps"

# derived
export PROJECT=$(gcloud config get-value project)
export CONF_DIR="${HOME_DIR}/${PROJECT}/${INSTANCE}"
