#!/bin/bash

CONFIG_FILE="config/secret-prod.yaml"

DB_NAME=$(yq .store.db < $CONFIG_FILE)
DB_PASS=$(yq .store.password < $CONFIG_FILE)

PGPASSWORD=$DB_PASS psql "host=127.0.0.1 port=5432 sslmode=disable user=postgres dbname=${DB_NAME}"
