#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

export INSTANCE_IP=$(gcloud sql instances describe ${INSTANCE} \
    --format='value(ipAddresses[0].ipAddress)')

PGPASSWORD=$(<"${CONF_DIR}/root_password") psql "sslmode=verify-ca sslrootcert=${CONF_DIR}/ca.pem sslcert=${CONF_DIR}/client.pem sslkey=${CONF_DIR}/client.key hostaddr=${INSTANCE_IP} port=5432 user=postgres dbname=${DB_NAME}"
