#!/bin/bash

NOW=$(date +%s)
DB_BUCKET="vuln-db-dumps"
CONFIG_FILE="config/secret-prod.yaml"

DB_NAME=$(yq .store.db < $CONFIG_FILE)

gcloud sql export sql $DB_NAME gs://$DB_BUCKET/$NOW.gz -d $DB_NAME
gsutil cp gs://$DB_BUCKET/$NOW.gz tools/db/dump/
gzip -d tools/db/dump/$NOW.gz
PGPASSWORD=test psql -h localhost -U postgres -d $DB_NAME < tools/db/sql/pre-restore.sql
PGPASSWORD=test psql -h localhost -U postgres -d $DB_NAME < tools/db/dump/$NOW
# PGPASSWORD=test psql -h localhost -U postgres -d $DB_NAME < tools/db/sql/post-restore.sql
gsutil rm gs://$DB_BUCKET/$NOW.gz
rm tools/db/dump/$NOW
