#!/bin/bash

NOW=$(date +%s)
DB_BUCKET="vuln-db-dumps"

gcloud sql export sql db gs://$DB_BUCKET/$NOW.gz -d vimp
gsutil cp gs://$DB_BUCKET/$NOW.gz tools/db/dump/
gzip -d tools/db/dump/$NOW.gz
PGPASSWORD=test psql -h localhost -U vimp -d vimp < tools/db/sql/pre-restore.sql
PGPASSWORD=test psql -h localhost -U vimp -d vimp < tools/db/dump/$NOW
PGPASSWORD=test psql -h localhost -U vimp -d vimp < tools/db/sql/post-restore.sql
gsutil rm gs://$DB_BUCKET/$NOW.gz
rm tools/db/dump/$NOW
