name: build

on:
  workflow_call:
    inputs:
      registry:
        description: 'Artifact Registry URI'
        required: true
        type: string
      image_name:
        description: 'Image name (e.g. my-image)'
        required: true
        type: string
      id_provider:
        description: 'OIDC provider'
        required: true
        type: string
      service_account:
        description: 'Email of the service account'
        required: true
        type: string
      go_version:
        description: 'Go version to use'
        required: true
        type: string
    outputs:
      digest:
        value: ${{ jobs.build.outputs.digest }}

permissions:
  contents: read

jobs:
  build:
    outputs:
      digest: ${{ steps.image.outputs.digest }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

    - name: Setup Go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9  # v4.0.0
      with:
        go-version: '${{ inputs.go_version }}'

    - run: go version

    - name: Cache Go Modules
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8  # v3.3.1
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Checkout Code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2

    - name: Tidy Modules
      run: |
        go mod tidy
        go mod vendor

    - name: Get Version
      run: |
        set -euo pipefail
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - id: auth
      name: Get GCP token
      uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033  # v1.1.1
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.id_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Install ko
      uses: ko-build/setup-ko@ace48d793556083a76f1e3e6068850c1f4a369aa  # v0.6

    - name: Authenticate ko
      env:
        AUTH_TOKEN: ${{ steps.auth.outputs.access_token }}
      run: |
        echo "${AUTH_TOKEN}" | ko login ${{ inputs.registry }} --username oauth2accesstoken --password-stdin

    # Note: ko build image ref will include BOTH, the tag AND digest of the image.
    - name: Build Image
      id: image
      env:
        KO_DOCKER_REPO: ${{ inputs.image_repo }}/${{ inputs.image_name }}
        GOFLAGS: "-ldflags=-X=main.version=${{ env.RELEASE_VERSION }}"
        COSIGN_EXPERIMENTAL: "true"
      run: |
        ko build internal/cmd/main.go --image-refs .digest --bare --tags ${{ env.RELEASE_VERSION }}
        echo "digest=$(cat .digest)" >> "$GITHUB_OUTPUT"
