name: on_tag
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'  # Only build tag with semantic versioning format

permissions:
  contents: read

jobs:

  build-app:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build.yaml
    with:
      image_name: app

  build-importer:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build.yaml
    with:
      image_name: importer